// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLD15mEHkyGSBcDv9Ci0j-JcbQbRAh-L4',
    appId: '1:1082668284689:web:64a6c371ac2968071beab0',
    messagingSenderId: '1082668284689',
    projectId: 'kazans-100fd',
    authDomain: 'kazans-100fd.firebaseapp.com',
    storageBucket: 'kazans-100fd.appspot.com',
    measurementId: 'G-6XTTW26DHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVyE07aE5t-FABjfYFXO-JFEtRlHM5DZk',
    appId: '1:1082668284689:android:86a11d8b33b0282a1beab0',
    messagingSenderId: '1082668284689',
    projectId: 'kazans-100fd',
    storageBucket: 'kazans-100fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgLUjXgejmwO6GoUIbWeKFRTIqdawO4sM',
    appId: '1:1082668284689:ios:396b6c81de6ca0ac1beab0',
    messagingSenderId: '1082668284689',
    projectId: 'kazans-100fd',
    storageBucket: 'kazans-100fd.appspot.com',
    iosClientId: '1082668284689-g211qnid935c1u7b9ehb99m863h22t94.apps.googleusercontent.com',
    iosBundleId: 'com.russiachinaforum',
  );
}
